#!/bin/bash

build() {
	local mod

	add_module dm-crypt
	add_module btrfs
	if [[ $CRYPTO_MODULES ]]; then
		for mod in $CRYPTO_MODULES; do
			add_module "$mod"
		done
	else
		add_all_modules '/crypto/'
	fi

	add_binary "cryptsetup"
	add_binary "dmsetup"
	add_file "/usr/lib/udev/rules.d/10-dm.rules"
	add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
	add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
	add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

	# Hook config
	add_file "/etc/initcpio/decrypt" "/etc/decrypt"

	add_runscript
}

help() {
	cat <<HELPEOF
Decrypts encrypted partitions from keys in a keystore partition.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4:
